apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
