apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
