apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume0
  namespace: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv1"
