apiVersion: batch/v1
kind: Job
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    metadata:
      name: grafpod
    spec:
      containers:
      - name: grafana
        image: 104005/myimage
        imagePullPolicy: Never
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    k8s-app: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
spec:
  type: NodePort
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    nodePort: 30300
  selector:
    k8s-app: grafana
